### ISSUE TITLE
关于angle_b的计算

### ISSUE THREAD

**Issue by Tomhardy13** [404nofound/Monocular_Distance_Detect#2]
angle_b理论上按照博客内容应该是目标点在图像中投影的点到图像中点的距离和焦距的反正切，但是代码中给的是angle_b = math.atan((v1 - self.H / 2) / fy)，v1这里是目标框的底部中点，H是相机离地面的高度，那么为何减去一半高度就是“目标点在图像中投影的点到图像中点的距离”呢？

**Comment by 404nofound** [comment]
这个角度的取值跟被测距物体的测距点有关，比如选择图像底部中心就测相机到底部中点的距离，选择图像中心点就测相机到中心的距离，根据实际需求来就行。
