### ISSUE TITLE
关于外参矩阵

### ISSUE THREAD

**Issue by xxysxka** [404nofound/Monocular_Distance_Detect#3]
![image](https://user-images.githubusercontent.com/61624151/217985504-67380f34-7d4f-452d-8e73-a8b728e737df.png)

您好，
请问外参矩阵里 这个 -1 要怎么理解呢？ 意思是 世界坐标系旋转之后，  再往下（相机坐标系的Y轴）平移 1 嘛？  
多谢你的答复。

**Comment by 404nofound** [comment]
您好，这个外参矩阵是用于相机坐标系和世界坐标系的转化的，代码的情况是相机离地1米的高度架在车上，两个坐标系3轴方向相同，所以只有平移矩阵作用没有旋转矩阵。如果你自定义的世界坐标系比较特殊，就可以通过外参矩阵来实现转化。

**Comment by xxysxka** [comment]
所以相机高度改变不仅要改 代码里的  H = 0.4， 还需要更改外参矩阵？

**Comment by 404nofound** [comment]
对的，代码里的H和外参矩阵都要修改的，这个代码我当时只修改测试了一下，可能有些参数没修改好。外参矩阵是要自己去算的，外参矩阵[0:3,0:3]是旋转矩阵，[0:3,3]是平移矩阵，最后扩了一维方便后面做矩阵运算的。单目测距还是有一定误差的。

**Comment by xxysxka** [comment]
了解。 多谢回答。
