### ISSUE TITLE
CameraParameters

### ISSUE THREAD

**Issue by xua123** [404nofound/Monocular_Distance_Detect#4]
我想问一下相机的内外参应该怎么设置，源码中的相机坐标系和世界坐标系轴方向是什么样子的？

**Comment by 404nofound** [comment]
内参要拿摄像机从不同角度拍棋盘格图片，用matlab标定相机参数（如果相机参数已知，可直接在内参矩阵的xls中替换成自己的参数）。相机坐标系，镜头方向为x轴，世界坐标系以道路前进方向为x轴，那么相机离地面的高度就是相机和世界坐标系上z轴的偏移量。
这个更新后的项目包含了测距和相对速度计算https://github.com/404nofound/Monocular_Distance_Velocity_Detect

**Comment by xua123** [comment]
好的，谢谢，我对标定这块了解的不多，那相机坐标系和世界坐标系的x,y,z方向是一致的嘛，能具体说一下各自的x ,y，z朝向嘛，如果相机坐标系和世界坐标系一致的话，外参矩阵只存在偏移量，但是我看代码中外参矩阵的旋转矩阵不是单位矩阵。

**Comment by 404nofound** [comment]
<img width="593" alt="1" src="https://github.com/404nofound/Monocular_Distance_Detect/assets/43553114/99a99856-f479-49a1-9e43-d7d0e0288dab">

**Comment by xua123** [comment]
能给个论文名称或者链接嘛？感谢感谢

**Comment by 404nofound** [comment]
相机坐标系和世界坐标系的方向是自定义的，旋转和偏移矩阵需要根据你的实际情况来改变。https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4405630

**Comment by xua123** [comment]
好的，感谢感谢
