### ISSUE TITLE
世界坐标系的建立有要求吗？

### ISSUE THREAD

**Issue by Sakura0v01** [404nofound/Monocular_Distance_Detect#7]
请问标定过程的外参需要更改吗？世界坐标系建立的依据是什么？还是世界坐标系不需要动，标定相机内参和确定角度跟高度就行

**Comment by 404nofound** [comment]
外参就是相机坐标系和世界坐标系之间的转换（偏移矩阵+旋转矩阵），世界坐标系的构建由你自主决定

**Comment by Sakura0v01** [comment]
好的谢谢解答，使用时图像要去畸变吗？

**Comment by 404nofound** [comment]
可以做矫正，但我测距测速是适用相邻车道和当前车道上近距离前方车辆的，一般不会出现在4个角。但如果是做车道线检测这些是要先去畸变的。

**Comment by Sakura0v01** [comment]
感谢解答

**Comment by Sakura0v01** [comment]
打扰了，还有一个问题不太理解代码中u, v, w, h = kuang[1] * self.W, kuang[2] * self.H, kuang[3] * self.W, kuang[4] * self.H目的是什么
![Uploading 2024-05-08 11-45-48屏幕截图.png…]()

**Comment by Sakura0v01** [comment]
打扰了，还有一个问题向您请教，代码中 
       u1 = u
        v1 = v + h / 2
        print('图像坐标系关键点：', u1, v1)
        #相机与水平线夹角, 默认为0 相机镜头正对前方，无倾斜
        #关键参数，不准会导致结果不对
        angle_a = 0
        angle_b = math.atan((v1 - self.H / 2) / fy)
我在看原理的时候这个abgle_b是（目标框底边中点到图像坐标系距离x轴的距离也就是）图像坐标系下的y值与焦距的反正切值
但是这样的话v1应该转到图像坐标系下吧，但是代码中好像还是像素坐标系下，请问是我哪里理解的有问题吗？

**Comment by 404nofound** [comment]
时间久了，有点记不清了。(v1 - self.H / 2) / fy这个应该就是图像坐标系里的点了。
<img width="500" alt="1715147695523" src="https://github.com/404nofound/Monocular_Distance_Detect/assets/43553114/9bd5f256-6dd9-4740-b369-07bb94730069">

**Comment by Sakura0v01** [comment]
理解了，非常感谢解答
