### ISSUE TITLE
using the weights trained on my own train dataset and wanted to apply this code for distance measurement, but there is something wrong

### ISSUE THREAD

**Issue by ShengnanDing** [404nofound/Monocular_Distance_Detect#8]
I use my own dataset to train yolov5,and get the sea_yolov5.pt.then I change the estimate_distance.py in line 241,247and 345.In 241 and 247 I change the names to my own classes,and change the 345 to the sea_yolov5.pt. and run :python estimate_distance.py --source xiangtan.mp4 --view-img
But It get something wrong:AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'C:\\Users\\azad\\Desktop\\project\\code\\Monocular_Distance_Detect-main\\models\\yolo.py'>
Can you help me how can I slove this problem? thank you so much

**Comment by 404nofound** [comment]
yolov5在发布过程中也有多次版本迭代，如果想换自己权重，得基于我用的这个版本（你可能得对比一下，我当时没记这个）在GitHub找对应target的yolov5，然后训练出来的权重文件就应该可以直接替换使用。

**Comment by ShengnanDing** [comment]
感谢！用yolov5版本5，可以使用啦！
